name: Issue assignment

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened, ready_for_review]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: OcelotWalrus
                  allowSelfAssign: true
    add-reviews:
        runs-on: ubuntu-latest
        steps:
            - uses: kentaro-m/auto-assign-action@v1.2.5
              with:
                configuration-path: '.github/auto-assign-config.yml' # Only needed if you use something other than .github/auto_assign.yml
